-- set the content of the repository window

    root(0)

	    tabs(1) 

		    tab(2, "A") 

			    combobox(3)
			    
					comboitem(4, "German") 
			    
						tabs(5) 

							tab(6, "a") 

								tabs(7)
								
									tab(8, "1") 
										
										listbox(9)	

											listitem(10, "German")

												listbox(11)

													listitem(12, "12R")

														Repository["German/12R-51R"] = Repository:new({"German/12R-51R", "German/12R-51R_f"})

													listitem(12, "38")

														Repository["German/38-94"] = Repository:new({"German/38-94", "German/38-94_f"})
											
											listitem(10, "French")
									tab(8, "2") 
									tab(8, "3") 
									tab(8, "4") 
									tab(8, "5") 
									tab(8, "6") 
							tab(6, "b")
							tab(6, "c")
							tab(6, "d") 
							tab(6, "e") 
							tab(6, "f") 
							tab(6, "e") 
							tab(6, "f")  
					comboitem(4, "French") 
		    tab(2, "B")
		    tab(2, "C")
		    tab(2, "D")
		    tab(2, "E")
		    tab(2, "F")
