
-- set the content of the repository window

root(0)

	tabs(1) 		

		tab(2, "German") 

				listbox(3)

					listitem(4, "Markers")

						listbox(5)

							listitem(6, "Markers")
								Repository["E"] = Repository:new({"E"})
								Repository["R"] = Repository:new({"R", "R_f"})
								Repository["I"] = Repository:new({"I"})							

							listitem(6, "Targets")
								Repository["GermanTarget1"] = Repository:new({"GermanTarget1"})
								Repository["GermanTarget2"] = Repository:new({"GermanTarget2"})
								Repository["GermanTarget3"] = Repository:new({"GermanTarget3"})
								Repository["GermanTarget4"] = Repository:new({"GermanTarget4"})
								Repository["GermanTarget5"] = Repository:new({"GermanTarget5"})
								Repository["GermanTarget6"] = Repository:new({"GermanTarget6"})
								Repository["GermanTarget7"] = Repository:new({"GermanTarget7"})
								Repository["GermanTarget8"] = Repository:new({"GermanTarget8"})
								Repository["GermanTarget9"] = Repository:new({"GermanTarget9"})
								Repository["GermanTarget10"] = Repository:new({"GermanTarget10"})

					listitem(4, "Units")
								Repository["ENGINEER"] = Repository:new({"ENGINEER", "ENGINEER_f"})
								Repository["BATTALION-1"] = Repository:new({"BATTALION-1", "BATTALION-1_f"})
								Repository["BATTALION-2"] = Repository:new({"BATTALION-2", "BATTALION-2_f"})
								
					
					listitem(4, "Artillery")
					
						listbox(5)
						
							listitem(6, "5/77 2")
								Repository["5-77-2"] = Repository:new({"5-77-2"})
								Repository["5-77-2"] = Repository:new({"5-77-2"})
								Repository["5-77-2"] = Repository:new({"5-77-2"})
								Repository["5-77-2"] = Repository:new({"5-77-2"})
							
							listitem(6, "5/77 3")
								Repository["5-77-3"] = Repository:new({"5-77-3"})
								Repository["5-77-3"] = Repository:new({"5-77-3"})
								Repository["5-77-3"] = Repository:new({"5-77-3"})
								Repository["5-77-3"] = Repository:new({"5-77-3"})
								
							listitem(6, "5/77 4")
								Repository["5-77-4"] = Repository:new({"5-77-4", "5-77-4_f"})
								Repository["5-77-4"] = Repository:new({"5-77-4", "5-77-4_f"})
								
							listitem(6, "5/105H")
								Repository["5-105H"] = Repository:new({"5-105H", "5-105H_f"})
								Repository["5-105H"] = Repository:new({"5-105H", "5-105H_f"})
								Repository["5-105H"] = Repository:new({"5-105H", "5-105H_f"})
								
							listitem(6, "5/150")
								Repository["5-150"] = Repository:new({"5-150", "5-150_f"})
								
							listitem(6, "5/130")
								Repository["5-130"] = Repository:new({"5-130", "5-130_f"})
								
							listitem(6, "5/100")
								Repository["5-100"] = Repository:new({"5-100", "5-100_f"})
								
							listitem(6, "5/150H")
								Repository["5-150H"] = Repository:new({"5-150H", "5-150H_f"})
								Repository["5-150H"] = Repository:new({"5-150H", "5-150H_f"})
								Repository["5-150H"] = Repository:new({"5-150H", "5-150H_f"})
								Repository["5-150H"] = Repository:new({"5-150H", "5-150H_f"})
								Repository["5-150H"] = Repository:new({"5-150H", "5-150H_f"})
								Repository["5-150H"] = Repository:new({"5-150H", "5-150H_f"})
								Repository["5-150H"] = Repository:new({"5-150H", "5-150H_f"})
								Repository["5-150H"] = Repository:new({"5-150H", "5-150H_f"})
								
							listitem(6, "5/210H")
								Repository["5-210H"] = Repository:new({"5-210H", "5-210H_f"})
								Repository["5-210H"] = Repository:new({"5-210H", "5-210H_f"})
								Repository["5-210H"] = Repository:new({"5-210H", "5-210H_f"})
								Repository["5-210H"] = Repository:new({"5-210H", "5-210H_f"})
								
							listitem(6, "5/305H")
								Repository["5-305H"] = Repository:new({"5-305H", "5-305H_f"})
								
							listitem(6, "5/380")
								Repository["5-380"] = Repository:new({"5-380", "5-380_f"})
							
							listitem(6, "5/420H 6")
								Repository["5-420H-6"] = Repository:new({"5-420H-6", "5-420H-6_f"})
								
							listitem(6, "5/420H 5")
								Repository["5-420H-5"] = Repository:new({"5-420H-5", "5-420H-5_f"})
						
					
					
					listitem(4, "Korps")
						Repository["VIR-KORPS"] = Repository:new({"VIR-KORPS", "VIR-KORPS_f"})
						Repository["VIIR-KORPS"] = Repository:new({"VIIR-KORPS", "VIIR-KORPS_f"})
						Repository["XVIII-KORPS"] = Repository:new({"XVIII-KORPS", "XVIII-KORPS_f"})
						Repository["III-KORPS"] = Repository:new({"III-KORPS", "III-KORPS_f"})
						Repository["XV-KORPS"] = Repository:new({"XV-KORPS", "XV-KORPS_f"})
						Repository["VR-KORPS"] = Repository:new({"VR-KORPS", "VR-KORPS_f"})
						Repository["V-KORPS"] = Repository:new({"V-KORPS", "V-KORPS_f"})
						Repository["XIV-KORPS"] = Repository:new({"XIV-KORPS", "XIV-KORPS_f"})
						Repository["XXIIR-KORPS"] = Repository:new({"XXIIR-KORPS", "XXIIR-KORPS_f"})
						Repository["ALP-KORPS"] = Repository:new({"ALP-KORPS", "ALP-KORPS_f"})
						Repository["XR-KORPS"] = Repository:new({"XR-KORPS", "XR-KORPS_f"})
						Repository["IB-KORPS"] = Repository:new({"IB-KORPS", "IB-KORPS_f"})
					
					
					listitem(4, "4th Division")
						Repository["4-14"] = Repository:new({"4-14", "4-14_f"})
						Repository["4-49"] = Repository:new({"4-49", "4-49_f"})
						Repository["4-140"] = Repository:new({"4-140", "4-140_f"})
						Repository["4-149"] = Repository:new({"4-149", "4-149_f"})
					
					
					listitem(4, "5th Division")
						Repository["5-8"] = Repository:new({"5-8", "5-8_f"})
						Repository["5-12G"] = Repository:new({"5-12G", "5-12G_f"})
						Repository["5-52"] = Repository:new({"5-52", "5-52_f"})
					
					listitem(4, "6th Division")
						Repository["6-3J"] = Repository:new({"6-3J", "6-3J_f"})
						Repository["6-20"] = Repository:new({"6-20", "6-20_f"})
						Repository["6-24"] = Repository:new({"6-24", "6-24_f"})
						Repository["6-64"] = Repository:new({"6-64", "6-64_f"})
					
					listitem(4, "6B Division")
						Repository["6B-10B"] = Repository:new({"6B-10B", "6B-10B_f"})
						Repository["6B-11B"] = Repository:new({"6B-11B", "6B-11B_f"})
						Repository["6B-13B"] = Repository:new({"6B-13B", "6B-13B_f"})
					
					listitem(4, "9R Division")
						Repository["9R-6R"] = Repository:new({"9R-6R", "9R-6R_f"})
						Repository["9R-19R"] = Repository:new({"9R-19R", "9R-19R_f"})
					
					listitem(4, "10R Division")
						Repository["10R-37R"] = Repository:new({"10R-37R", "10R-37R_f"})
						Repository["10R-98R"] = Repository:new({"10R-98R", "10R-98R_f"})
						Repository["10R-155"] = Repository:new({"10R-155", "10R-155_f"})
					
					listitem(4, "11B Division")
						Repository["11B-3B"] = Repository:new({"11B-3B", "11B-3B_f"})
						Repository["11B-13B"] = Repository:new({"11B-13B", "11B-13B_f"})
						Repository["11B-22B"] = Repository:new({"11B-22B", "11B-22B_f"})
					
					listitem(4, "11R Division")
						Repository["11R-10R"] = Repository:new({"11R-10R", "11R-10R_f"})
						Repository["11R-22"] = Repository:new({"11R-22", "11R-22_f"})
						Repository["11R-156"] = Repository:new({"11R-156", "11R-156_f"})
					
					listitem(4, "12R Division")
						Repository["12R-23R"] = Repository:new({"12R-23R", "12R-23R_f"})
						Repository["12R-38R"] = Repository:new({"12R-38R", "12R-38R_f"})
						Repository["12R-51R"] = Repository:new({"12R-51R", "12R-51R_f"})
							
					listitem(4, "13R Division")
						Repository["13R-7J"] = Repository:new({"13R-7J", "13R-7J_f"})
						Repository["13R-13R"] = Repository:new({"13R-13R", "13R-13R_f"})
						Repository["13R-39"] = Repository:new({"13R-39", "13R-39_f"})
						Repository["13R-57R"] = Repository:new({"13R-57R", "13R-57R_f"})
					
					listitem(4, "14R Division")
						Repository["14R-16"] = Repository:new({"14R-16", "14R-16_f"})
						Repository["14R-53R"] = Repository:new({"14R-53R", "14R-53R_f"})
						Repository["14R-159"] = Repository:new({"14R-159", "14R-159_f"})
					
					listitem(4, "21st Division")
						Repository["21-80"] = Repository:new({"21-80", "21-80_f"})
						Repository["21-81"] = Repository:new({"21-81", "21-81_f"})
						Repository["21-87"] = Repository:new({"21-87", "21-87_f"})
					
					listitem(4, "22R Division")
						Repository["22R-71R"] = Repository:new({"22R-71R", "22R-71R_f"})
						Repository["22R-82R"] = Repository:new({"22R-82R", "22R-82R_f"})
						Repository["22R-94R"] = Repository:new({"22R-94R", "22R-94R_f"})
					
					listitem(4, "25st Division")
						Repository["25-115"] = Repository:new({"25-115", "25-115_f"})
						Repository["25-116"] = Repository:new({"25-116", "25-116_f"})
						Repository["25-117"] = Repository:new({"25-117", "25-117_f"})
					
					listitem(4, "30st Division")
						Repository["30-99"] = Repository:new({"30-99", "30-99_f"})
						Repository["30-105"] = Repository:new({"30-105", "30-105_f"})
						Repository["30-143"] = Repository:new({"30-143", "30-143_f"})
					
					listitem(4, "33R Division")
						Repository["33R-67R"] = Repository:new({"33R-67R", "33R-67R_f"})
						Repository["33R-130R"] = Repository:new({"33R-130R", "33R-130R_f"})
						Repository["33R-364"] = Repository:new({"33R-364", "33R-364_f"})
					
					listitem(4, "38st Division")
						Repository["38-94"] = Repository:new({"38-94", "38-94_f"})
						Repository["38-95"] = Repository:new({"38-95", "38-95_f"})
						Repository["38-96"] = Repository:new({"38-96", "38-96_f"})
					
					listitem(4, "39st Division")
						Repository["39-126"] = Repository:new({"39-126", "39-126_f"})
						Repository["39-132"] = Repository:new({"39-132", "39-132_f"})
						Repository["39-172"] = Repository:new({"39-172", "39-172_f"})
					
					listitem(4, "54st Division")
						Repository["54-27R"] = Repository:new({"54-27R", "54-27R_f"})
						Repository["54-84"] = Repository:new({"54-84", "54-84_f"})
						Repository["54-90R"] = Repository:new({"54-90R", "54-90R_f"})
					
					listitem(4, "58st Division")
						Repository["58-106"] = Repository:new({"58-106", "58-106_f"})
						Repository["58-107"] = Repository:new({"58-107", "58-107_f"})
						Repository["58-120R"] = Repository:new({"58-120R", "58-120R_f"})
								
					listitem(4, "113st Division")
						Repository["113-32R"] = Repository:new({"113-32R", "113-32R_f"})
						Repository["113-36F"] = Repository:new({"113-36F", "113-36F_f"})
						Repository["113-48"] = Repository:new({"113-48", "113-48_f"})
									
					listitem(4, "121st Division")
						Repository["121-7R"] = Repository:new({"121-7R", "121-7R_f"})
						Repository["121-56R"] = Repository:new({"121-56R", "121-56R_f"})
						Repository["121-60"] = Repository:new({"121-60", "121-60_f"})
					
					listitem(4, "192Xst Division")
						Repository["192X-25B"] = Repository:new({"192X-25B", "192X-25B_f"})
						Repository["192X-192"] = Repository:new({"192X-192", "192X-192_f"})
						Repository["192X-193"] = Repository:new({"192X-193", "192X-193_f"})
					
					listitem(4, "AC Division")
						Repository["AC-1BJ"] = Repository:new({"AC-1BJ", "AC-1BJ_f"})
						Repository["AC-2J"] = Repository:new({"AC-2J", "AC-2J_f"})
						Repository["AC-3J"] = Repository:new({"AC-3J", "AC-3J_f"})
						Repository["AC-BI"] = Repository:new({"AC-BI", "AC-BI_f"})

		tab(2, "French") 

			listbox(3)

					listitem(4, "Markers")

						listbox(5)

							listitem(6, "Markers")
								Repository["75"] = Repository:new({"75"})
								Repository["E-F"] = Repository:new({"E-F"})
								Repository["R-F"] = Repository:new({"R-F", "R-F_f"})
								Repository["I-F"] = Repository:new({"I-F"})							

							listitem(6, "Targets")
								Repository["FrenchTarget1"] = Repository:new({"FrenchTarget1"})
								Repository["FrenchTarget2"] = Repository:new({"FrenchTarget2"})
								Repository["FrenchTarget3"] = Repository:new({"FrenchTarget3"})
								Repository["FrenchTarget4"] = Repository:new({"FrenchTarget4"})
								Repository["FrenchTarget5"] = Repository:new({"FrenchTarget5"})
								Repository["FrenchTarget6"] = Repository:new({"FrenchTarget6"})
								Repository["FrenchTarget7"] = Repository:new({"FrenchTarget7"})
								Repository["FrenchTarget8"] = Repository:new({"FrenchTarget8"})
								Repository["FrenchTarget9"] = Repository:new({"FrenchTarget9"})
								Repository["FrenchTarget10"] = Repository:new({"FrenchTarget10"})

					listitem(4, "Units")
								Repository["59-C"] = Repository:new({"59-C", "59-C_f"})
								Repository["BRIGADE-3"] = Repository:new({"BRIGADE-3", "BRIGADE-3_f"})
								Repository["BRIGADE-4"] = Repository:new({"BRIGADE-4", "BRIGADE-4_f"})
								
					listitem(4, "Artillery")
					
						listbox(5)
						
							listitem(6, "2/75 2")
								Repository["2-75"] = Repository:new({"2-75", "2-75_f"})
								Repository["2-75"] = Repository:new({"2-75", "2-75_f"})
								Repository["2-75"] = Repository:new({"2-75", "2-75_f"})
								Repository["2-75"] = Repository:new({"2-75", "2-75_f"})
								Repository["2-75"] = Repository:new({"2-75", "2-75_f"})
								Repository["2-75"] = Repository:new({"2-75", "2-75_f"})
								Repository["2-75"] = Repository:new({"2-75", "2-75_f"})
								Repository["2-75"] = Repository:new({"2-75", "2-75_f"})
							
							listitem(6, "2/75 3")
								Repository["3-75"] = Repository:new({"3-75", "3-75_f"})
								Repository["3-75"] = Repository:new({"3-75", "3-75_f"})
								Repository["3-75"] = Repository:new({"3-75", "3-75_f"})
								
							listitem(6, "2/75 4")
								Repository["4-75"] = Repository:new({"4-75", "4-75_f"})
								
							listitem(6, "2/90")
								Repository["2-90"] = Repository:new({"2-90", "2-90_f"})
								
							listitem(6, "2/105")
								Repository["2-105"] = Repository:new({"2-105", "2-105_f"})
								
							listitem(6, "2/120")
								Repository["2-120"] = Repository:new({"2-120", "2-120_f"})
								
							listitem(6, "2/155H 3")
								Repository["2-155H"] = Repository:new({"2-155H", "2-155H_f"})	
								Repository["2-155H"] = Repository:new({"2-155H", "2-155H_f"})	
								
							listitem(6, "2/155H 4")
								Repository["4-155H"] = Repository:new({"4-155H", "4-155H_f"})	
								
							listitem(6, "2/220")
								Repository["2-220"] = Repository:new({"2-220", "2-220_f"})	
								
							listitem(6, "2/240H")
								Repository["2-240H"] = Repository:new({"2-240H", "2-240H_f"})
								
							listitem(6, "2/280H")
								Repository["2-280H"] = Repository:new({"2-280H", "2-280H_f"})
								
							listitem(6, "2/305H")
								Repository["2-305H"] = Repository:new({"2-305H", "2-305H_f"})	
								
							listitem(6, "2/270H")
								Repository["2-270H"] = Repository:new({"2-270H", "2-270H_f"})	
								
							listitem(6, "2/400")
								Repository["2-400"] = Repository:new({"2-400", "2-400_f"})	
								Repository["2-400"] = Repository:new({"2-400", "2-400_f"})
							
							
					listitem(4, "Corps")
						Repository["I-CORPS"] = Repository:new({"I-CORPS", "I-CORPS_f"})
						Repository["II-CORPS"] = Repository:new({"II-CORPS", "II-CORPS_f"})
						Repository["III-CORPS"] = Repository:new({"III-CORPS", "III-CORPS_f"})
						Repository["VII-CORPS"] = Repository:new({"VII-CORPS", "VII-CORPS_f"})
						Repository["XII-CORPS"] = Repository:new({"XII-CORPS", "XII-CORPS_f"})
						Repository["XIII-CORPS"] = Repository:new({"XIII-CORPS", "XIII-CORPS_f"})
						Repository["XIV-CORPS"] = Repository:new({"XIV-CORPS", "XIV-CORPS_f"})
						Repository["XX-CORPS"] = Repository:new({"XX-CORPS", "XX-CORPS_f"})
						Repository["XXI-CORPS"] = Repository:new({"XXI-CORPS", "XXI-CORPS_f"})
						Repository["XXX-CORPS"] = Repository:new({"XXX-CORPS", "XXX-CORPS_f"})
						Repository["XXXII-CORPS"] = Repository:new({"XXXII-CORPS", "XXXII-CORPS_f"})
						Repository["XXXIII-CORPS"] = Repository:new({"XXXIII-CORPS", "XXXIII-CORPS_f"})
						
					listitem(4, "I corps")
						Repository["I-1"] = Repository:new({"I-1", "I-1_f"})
						Repository["I-22"] = Repository:new({"I-22", "I-22_f"})
						Repository["I-39"] = Repository:new({"I-39", "I-39_f"})
						Repository["I-42"] = Repository:new({"I-42", "I-42_f"})
						Repository["I-59"] = Repository:new({"I-59", "I-59_f"})
						
					listitem(4, "II corps")
						Repository["II-3"] = Repository:new({"II-3", "II-3_f"})
						Repository["II-4"] = Repository:new({"II-4", "II-4_f"})
						Repository["II-16"] = Repository:new({"II-16", "II-16_f"})
						Repository["II-68"] = Repository:new({"II-68", "II-68_f"})
						Repository["II-132"] = Repository:new({"II-132", "II-132_f"})
									
					listitem(4, "III corps")
						Repository["III-5"] = Repository:new({"III-5", "III-5_f"})
						Repository["III-6"] = Repository:new({"III-6", "III-6_f"})
						Repository["III-128"] = Repository:new({"III-128", "III-128_f"})
						Repository["III-130"] = Repository:new({"III-130", "III-130_f"})
						
					listitem(4, "VII corps")
						Repository["VII-25"] = Repository:new({"VII-25", "VII-25_f"})
						Repository["VII-29"] = Repository:new({"VII-29", "VII-29_f"})
						Repository["VII-40"] = Repository:new({"VII-40", "VII-40_f"})
						Repository["VII-67"] = Repository:new({"VII-67", "VII-67_f"})
					
					listitem(4, "XII corps")
						Repository["XII-23"] = Repository:new({"XII-23", "XII-23_f"})
						Repository["XII-56"] = Repository:new({"XII-56", "XII-56_f"})
						
					listitem(4, "XIII corps")
						Repository["XIII-26"] = Repository:new({"XIII-26", "XIII-26_f"})
						Repository["XIII-34"] = Repository:new({"XIII-34", "XIII-34_f"})
						Repository["XIII-76"] = Repository:new({"XIII-76", "XIII-76_f"})
						Repository["XIII-120"] = Repository:new({"XIII-120", "XIII-120_f"})
						
					listitem(4, "XIV corps")
						Repository["XIV-27"] = Repository:new({"XIV-27", "XIV-27_f"})
						Repository["XIV-28"] = Repository:new({"XIV-28", "XIV-28_f"})
					
					listitem(4, "XX corps")
						Repository["XX-2"] = Repository:new({"XX-2", "XX-2_f"})
						Repository["XX-11"] = Repository:new({"XX-11", "XX-11_f"})
						Repository["XX-17"] = Repository:new({"XX-17", "XX-17_f"})
						Repository["XX-18"] = Repository:new({"XX-18", "XX-18_f"})
						Repository["XX-43"] = Repository:new({"XX-43", "XX-43_f"})
						Repository["XX-48"] = Repository:new({"XX-48", "XX-48_f"})
						Repository["XX-153"] = Repository:new({"XX-153", "XX-153_f"})
					
					listitem(4, "XXI corps")
						Repository["XXI-13"] = Repository:new({"XXI-13", "XXI-13_f"})
						Repository["XXI-70"] = Repository:new({"XXI-70", "XXI-70_f"})
						Repository["XXI-77"] = Repository:new({"XXI-77", "XXI-77_f"})
					
					listitem(4, "XXX corps")
						Repository["XXX-14"] = Repository:new({"XXX-14", "XXX-14_f"})
						Repository["XXX-37"] = Repository:new({"XXX-37", "XXX-37_f"})
						Repository["XXX-51R"] = Repository:new({"XXX-51R", "XXX-51R_f"})
						Repository["XXX-72R"] = Repository:new({"XXX-72R", "XXX-72R_f"})
						Repository["XXX-106"] = Repository:new({"XXX-106", "XXX-106_f"})
					
					listitem(4, "XXXII corps")
						Repository["XXXII-69"] = Repository:new({"XXXII-69", "XXXII-69_f"})
					

		tab(2, "Markers") 

			Repository["SMOKE"] = Repository:new({"SMOKE"})
			Repository["CREEPING"] = Repository:new({"CREEPING"})
			Repository["LIFTING"] = Repository:new({"LIFTING"})
			Repository["SECONDARY"] = Repository:new({"SECONDARY"})
			Repository["CONSOLIDATE"] = Repository:new({"CONSOLIDATE"})
			Repository["GAS"] = Repository:new({"GAS"})
			Repository["NIGHT"] = Repository:new({"NIGHT"})
			Repository["FLAME"] = Repository:new({"FLAME"})
			Repository["D"] = Repository:new({"D", "D_f"})
			Repository["D_f"] = Repository:new({"D_f", "D"})
